version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    assignees:
      - pdugan20
    reviewers:
      - pdugan20
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    assignees:
      - pdugan20
    reviewers:
      - pdugan20
